#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    machine: true

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx256m
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "single-module/build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: cd single-module && ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.m2
            - ~/.gradle
          key: v1-dependencies-{{ checksum "single-module/build.gradle" }}

      # run tests!
      - run: cd single-module && ./build-and-test-all.sh
      - run: cd single-module && ./build-and-test-all-eventuate-local.sh
      - run: cd single-module && ./build-and-test-all-eventuate-local-postgres.sh